/* Nestora Realty — property listings (Germany) */
const PROPERTIES = [
  {
    id: 1,
    title: {"en": "Bright 3-Room Altbau Apartment", "de": "Helle 3-Zimmer-Altbauwohnung"},
    status: "rent",
    type: "apartment",
    price: 822,
    priceNote: "per_month",
    location: {"en": "Bilk, Düsseldorf", "de": "Bilk, Düsseldorf"},
    beds: 2, baths: 1, sqm: 108,
    badge: {"en": "Garden", "de": "Garten"},
    featured: true,
    description: {"en": "Classic Altbau with high stucco ceilings and wooden floors, freshly renovated in the heart of Bilk. U/S-Bahn, cafés and parks in walking distance.", "de": "Klassischer Altbau mit Stuckdecken und Holzböden, frisch renoviert im Herzen von Bilk. U/S-Bahn, Cafés und Parks in Gehweite."},
    features: {"en": ["Altbau charm", "Cellar space", "Fitted kitchen", "Wooden floors", "Balcony", "Stucco ceilings", "Daylight bathroom"], "de": ["Altbau-Charme", "Kellerabteil", "Einbauküche", "Holzböden", "Balkon", "Stuckdecken", "Tageslichtbad"]},
    image: "assets/img/props/55/p1.jpg",
    gallery: ["assets/img/props/55/p1.jpg", "assets/img/props/55/p2.jpg", "assets/img/props/55/p3.jpg", "assets/img/props/55/p4.jpg", "assets/img/props/55/p5.jpg"]
  },
  {
    id: 2,
    title: {"en": "Detached House with Mature Garden", "de": "Freistehendes Haus mit altem Garten"},
    status: "sale",
    type: "detached",
    price: 730000,
    location: {"en": "Loschwitz, Dresden", "de": "Loschwitz, Dresden"},
    beds: 6, baths: 3, sqm: 288,
    badge: {"en": "Luxury", "de": "Luxus"},
    featured: true,
    description: {"en": "A well-kept detached home with 288 m² of living space, a mature garden and a quiet, established neighbourhood in Loschwitz.", "de": "Ein gepflegtes freistehendes Haus mit 288 m² Wohnfläche, altem Baumbestand und ruhiger, etablierter Nachbarschaft in Loschwitz, Dresden."},
    features: {"en": ["Architect design", "Garden & terrace", "Smart home", "Underfloor heating", "Car port"], "de": ["Architektenhaus", "Garten & Terrasse", "Smart Home", "Fußbodenheizung", "Carport"]},
    image: "assets/img/props/24/p1.jpg",
    gallery: ["assets/img/props/24/p1.jpg", "assets/img/props/24/p2.jpg", "assets/img/props/24/p3.jpg", "assets/img/props/24/p4.jpg", "assets/img/props/24/p5.jpg"]
  },
  {
    id: 3,
    title: {"en": "Historic Half-Timbered House, Modernized", "de": "Historisches Fachwerkhaus, modernisiert"},
    status: "sale",
    type: "detached",
    price: 660000,
    location: {"en": "Zittau, Germany", "de": "Zittau (Sachsen)"},
    beds: 3, baths: 3, sqm: 162,
    description: {"en": "Living behind a listed timber facade: this 162 m² house in Zittau combines 19th-century charm with a contemporary interior, underfloor heating and a renovated roof.", "de": "Wohnen hinter denkmalgeschützter Fachwerkfassade: dieses 162 m² Haus in Zittau (Sachsen) verbindet Charme des 19. Jahrhunderts mit modernem Interieur, Fußbodenheizung und saniertem Dach."},
    features: {"en": ["Listed landmark charm", "Renovated 2021", "Fitted kitchen", "Timber facade restored", "Energy certificate class C", "Underfloor heating"], "de": ["Denkmal-Charme", "Saniert 2021", "Einbauküche", "Fassade restauriert", "Energieklasse C", "Fußbodenheizung"]},
    image: "assets/img/props/3/p1.jpg",
    gallery: ["assets/img/props/3/p1.jpg", "assets/img/props/3/p2.jpg", "assets/img/props/3/p3.jpg", "assets/img/props/3/p4.jpg", "assets/img/props/3/p5.jpg"]
  },
  {
    id: 4,
    title: {"en": "Detached House with Mature Garden", "de": "Freistehendes Haus mit altem Garten"},
    status: "sale",
    type: "detached",
    price: 830000,
    location: {"en": "Connewitz, Leipzig", "de": "Connewitz, Leipzig"},
    beds: 6, baths: 4, sqm: 405,
    badge: {"en": "Luxury", "de": "Luxus"},
    description: {"en": "A well-kept detached home with 405 m² of living space, a mature garden and a quiet, established neighbourhood in Connewitz.", "de": "Ein gepflegtes freistehendes Haus mit 405 m² Wohnfläche, altem Baumbestand und ruhiger, etablierter Nachbarschaft in Connewitz, Leipzig."},
    features: {"en": ["Smart home", "Fitted kitchen", "Underfloor heating", "Garden & terrace", "Architect design", "Energy class A"], "de": ["Smart Home", "Einbauküche", "Fußbodenheizung", "Garten & Terrasse", "Architektenhaus", "Energieklasse A"]},
    image: "assets/img/props/23/p1.jpg",
    gallery: ["assets/img/props/23/p1.jpg", "assets/img/props/23/p2.jpg", "assets/img/props/23/p3.jpg", "assets/img/props/23/p4.jpg", "assets/img/props/23/p5.jpg"]
  },
  {
    id: 5,
    title: {"en": "Historic Half-Timbered House, Modernized", "de": "Historisches Fachwerkhaus, modernisiert"},
    status: "sale",
    type: "detached",
    price: 550000,
    location: {"en": "Rothenburg ob der Tauber, Germany", "de": "Rothenburg ob der Tauber (Bayern)"},
    beds: 5, baths: 2, sqm: 181,
    featured: true,
    description: {"en": "Living behind a listed timber facade: this 181 m² house in Rothenburg ob der Tauber combines 19th-century charm with a contemporary interior, underfloor heating and a renovated roof.", "de": "Wohnen hinter denkmalgeschützter Fachwerkfassade: dieses 181 m² Haus in Rothenburg ob der Tauber (Bayern) verbindet Charme des 19. Jahrhunderts mit modernem Interieur, Fußbodenheizung und saniertem Dach."},
    features: {"en": ["Underfloor heating", "Energy certificate class C", "Timber facade restored", "Courtyard garden", "Fitted kitchen"], "de": ["Fußbodenheizung", "Energieklasse C", "Fassade restauriert", "Innenhofgarten", "Einbauküche"]},
    image: "assets/img/props/7/p1.jpg",
    gallery: ["assets/img/props/7/p1.jpg", "assets/img/props/7/p2.jpg", "assets/img/props/7/p3.jpg", "assets/img/props/7/p4.jpg", "assets/img/props/7/p5.jpg"]
  },
  {
    id: 6,
    title: {"en": "Bright 3-Room Altbau Apartment", "de": "Helle 3-Zimmer-Altbauwohnung"},
    status: "rent",
    type: "apartment",
    price: 1372,
    priceNote: "per_month",
    location: {"en": "Nordend, Frankfurt", "de": "Nordend, Frankfurt am Main"},
    beds: 2, baths: 1, sqm: 128,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "Classic Altbau with high stucco ceilings and wooden floors, freshly renovated in the heart of Nordend. U/S-Bahn, cafés and parks in walking distance.", "de": "Klassischer Altbau mit Stuckdecken und Holzböden, frisch renoviert im Herzen von Nordend. U/S-Bahn, Cafés und Parks in Gehweite."},
    features: {"en": ["Altbau charm", "Stucco ceilings", "Balcony", "Wooden floors", "Daylight bathroom"], "de": ["Altbau-Charme", "Stuckdecken", "Balkon", "Holzböden", "Tageslichtbad"]},
    image: "assets/img/props/46/p1.jpg",
    gallery: ["assets/img/props/46/p1.jpg", "assets/img/props/46/p2.jpg", "assets/img/props/46/p3.jpg", "assets/img/props/46/p4.jpg", "assets/img/props/46/p5.jpg"]
  },
  {
    id: 7,
    title: {"en": "Energy-Efficient Family Home", "de": "Energieeffizientes Familienhaus"},
    status: "sale",
    type: "detached",
    price: 2200000,
    location: {"en": "Rotenberg, Stuttgart", "de": "Rotenberg, Stuttgart"},
    beds: 4, baths: 4, sqm: 368,
    description: {"en": "A contemporary family home built to Kf70 standard: bright rooms, generous layout, air-to-air heat pump and a car port. Ideal for buyers moving in right away.", "de": "Ein modernes Familienhaus in Kf70-Bauweise: helle Räume, großzügiger Grundriss, Luft-Wasser-Wärmepumpe und Carport. Ideal für sofort Einziehende."},
    features: {"en": ["Underfloor heating", "Energy class A", "Garden & terrace", "Car port", "Smart home"], "de": ["Fußbodenheizung", "Energieklasse A", "Garten & Terrasse", "Carport", "Smart Home"]},
    image: "assets/img/props/25/p1.jpg",
    gallery: ["assets/img/props/25/p1.jpg", "assets/img/props/25/p2.jpg", "assets/img/props/25/p3.jpg", "assets/img/props/25/p4.jpg", "assets/img/props/25/p5.jpg"]
  },
  {
    id: 8,
    title: {"en": "Maisonette Apartment with Roof Terrace", "de": "Maisonette-Wohnung mit Dachterrasse"},
    status: "sale",
    type: "duplex",
    price: 670000,
    location: {"en": "Nippes, Cologne", "de": "Nippes, Köln"},
    beds: 4, baths: 3, sqm: 157,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "A maisonette over two levels with a private roof terrace, open kitchen-living area and views across Nippes.", "de": "Eine Maisonette über zwei Ebenen mit privater Dachterrasse, offener Küchen-Wohnfläche und Blick über Nippes, Köln."},
    features: {"en": ["Underfloor heating", "Roof terrace", "Elevator", "Two balconies", "Two levels", "Open kitchen-living"], "de": ["Fußbodenheizung", "Dachterrasse", "Aufzug", "Zwei Balkone", "Zwei Ebenen", "Offene Küchen-Wohnfläche"]},
    image: "assets/img/props/44/p1.jpg",
    gallery: ["assets/img/props/44/p1.jpg", "assets/img/props/44/p2.jpg", "assets/img/props/44/p3.jpg", "assets/img/props/44/p4.jpg", "assets/img/props/44/p5.jpg"]
  },
  {
    id: 9,
    title: {"en": "Penthouse with Roof Terrace", "de": "Penthouse mit Dachterrasse"},
    status: "rent",
    type: "penthouse",
    price: 4258,
    priceNote: "per_month",
    location: {"en": "Bornheim, Frankfurt", "de": "Bornheim, Frankfurt am Main"},
    beds: 4, baths: 3, sqm: 132,
    featured: true,
    description: {"en": "A top-floor penthouse with wrap-around roof terrace and open skyline views over Bornheim. Elevator access, underfloor heating and two parking bays in the building's garage.", "de": "Ein Penthouse im Obergeschoss mit umlaufender Dachterrasse und freiem Blick über Bornheim. Aufzug, Fußbodenheizung und zwei Stellplätze im Haus."},
    features: {"en": ["Underfloor heating", "Elevator", "Skyline view", "Roof terrace", "Concierge"], "de": ["Fußbodenheizung", "Aufzug", "Ausblick", "Dachterrasse", "Concierge"]},
    image: "assets/img/props/61/p1.jpg",
    gallery: ["assets/img/props/61/p1.jpg", "assets/img/props/61/p2.jpg", "assets/img/props/61/p3.jpg", "assets/img/props/61/p4.jpg", "assets/img/props/61/p5.jpg"]
  },
  {
    id: 10,
    title: {"en": "Apartment in Historic Half-Timbered House", "de": "Wohnung im historischen Fachwerkhaus"},
    status: "rent",
    type: "apartment",
    price: 979,
    priceNote: "per_month",
    location: {"en": "Lübeck, Germany", "de": "Lübeck"},
    beds: 2, baths: 2, sqm: 64,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "Bright 64 m² apartment on the upper floor of a landmark half-timbered house in the old town of Lübeck. High ceilings, wooden floors and a view over the rooftops.", "de": "Helle 64 m² Wohnung im Obergeschoss eines denkmalgeschützten Fachwerkhauses in der Altstadt von Lübeck. Hohe Decken, Holzböden und Blick über die Dächer."},
    features: {"en": ["Fitted kitchen", "Cellar space", "High ceilings", "Wooden floors", "Old-town location", "Rooftop view"], "de": ["Einbauküche", "Kellerabteil", "Hohe Decken", "Holzböden", "Altstadtlage", "Blick über Dächer"]},
    image: "assets/img/props/21/p1.jpg",
    gallery: ["assets/img/props/21/p1.jpg", "assets/img/props/21/p2.jpg", "assets/img/props/21/p3.jpg", "assets/img/props/21/p4.jpg", "assets/img/props/21/p5.jpg"]
  },
  {
    id: 11,
    title: {"en": "Maisonette Apartment with Roof Terrace", "de": "Maisonette-Wohnung mit Dachterrasse"},
    status: "sale",
    type: "duplex",
    price: 600000,
    location: {"en": "St. Johannis, Nuremberg", "de": "St. Johannis, Nürnberg"},
    beds: 3, baths: 2, sqm: 149,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "A maisonette over two levels with a private roof terrace, open kitchen-living area and views across St. Johannis.", "de": "Eine Maisonette über zwei Ebenen mit privater Dachterrasse, offener Küchen-Wohnfläche und Blick über St. Johannis, Nürnberg."},
    features: {"en": ["Open kitchen-living", "Two levels", "Elevator", "Two balconies", "Underfloor heating", "Roof terrace"], "de": ["Offene Küchen-Wohnfläche", "Zwei Ebenen", "Aufzug", "Zwei Balkone", "Fußbodenheizung", "Dachterrasse"]},
    image: "assets/img/props/43/p1.jpg",
    gallery: ["assets/img/props/43/p1.jpg", "assets/img/props/43/p2.jpg", "assets/img/props/43/p3.jpg", "assets/img/props/43/p4.jpg", "assets/img/props/43/p5.jpg"]
  },
  {
    id: 12,
    title: {"en": "Renovated Half-Timbered House in Hannoversch Münden", "de": "Renoviertes Fachwerkhaus in Hannoversch Münden"},
    status: "sale",
    type: "detached",
    price: 390000,
    location: {"en": "Hannoversch Münden, Germany", "de": "Hannoversch Münden"},
    beds: 3, baths: 3, sqm: 196,
    description: {"en": "A beautifully renovated half-timbered house in Hannoversch Münden. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 196 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Hannoversch Münden. Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 196 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Fitted kitchen", "Energy certificate class C", "Renovated 2021", "Courtyard garden", "Underfloor heating", "Listed landmark charm", "Timber facade restored"], "de": ["Einbauküche", "Energieklasse C", "Saniert 2021", "Innenhofgarten", "Fußbodenheizung", "Denkmal-Charme", "Fassade restauriert"]},
    image: "assets/img/props/13/p1.jpg",
    gallery: ["assets/img/props/13/p1.jpg", "assets/img/props/13/p2.jpg", "assets/img/props/13/p3.jpg", "assets/img/props/13/p4.jpg", "assets/img/props/13/p5.jpg"]
  },
  {
    id: 13,
    title: {"en": "Energy-Efficient Family Home", "de": "Energieeffizientes Familienhaus"},
    status: "sale",
    type: "detached",
    price: 1450000,
    location: {"en": "Friedenau, Berlin", "de": "Friedenau, Berlin"},
    beds: 4, baths: 4, sqm: 236,
    badge: {"en": "Luxury", "de": "Luxus"},
    description: {"en": "A contemporary family home built to Kf70 standard: bright rooms, generous layout, air-to-air heat pump and a car port. Ideal for buyers moving in right away.", "de": "Ein modernes Familienhaus in Kf70-Bauweise: helle Räume, großzügiger Grundriss, Luft-Wasser-Wärmepumpe und Carport. Ideal für sofort Einziehende."},
    features: {"en": ["Fitted kitchen", "Garden & terrace", "Underfloor heating", "Car port", "Energy class A", "Smart home"], "de": ["Einbauküche", "Garten & Terrasse", "Fußbodenheizung", "Carport", "Energieklasse A", "Smart Home"]},
    image: "assets/img/props/27/p1.jpg",
    gallery: ["assets/img/props/27/p1.jpg", "assets/img/props/27/p2.jpg", "assets/img/props/27/p3.jpg", "assets/img/props/27/p4.jpg", "assets/img/props/27/p5.jpg"]
  },
  {
    id: 14,
    title: {"en": "Apartment in Historic Half-Timbered House", "de": "Wohnung im historischen Fachwerkhaus"},
    status: "rent",
    type: "apartment",
    price: 623,
    priceNote: "per_month",
    location: {"en": "Dinkelsbühl, Germany", "de": "Dinkelsbühl"},
    beds: 3, baths: 1, sqm: 70,
    featured: true,
    description: {"en": "Bright 70 m² apartment on the upper floor of a landmark half-timbered house in the old town of Dinkelsbühl. High ceilings, wooden floors and a view over the rooftops.", "de": "Helle 70 m² Wohnung im Obergeschoss eines denkmalgeschützten Fachwerkhauses in der Altstadt von Dinkelsbühl. Hohe Decken, Holzböden und Blick über die Dächer."},
    features: {"en": ["Wooden floors", "High ceilings", "Old-town location", "Cellar space", "Fitted kitchen", "Rooftop view"], "de": ["Holzböden", "Hohe Decken", "Altstadtlage", "Kellerabteil", "Einbauküche", "Blick über Dächer"]},
    image: "assets/img/props/20/p1.jpg",
    gallery: ["assets/img/props/20/p1.jpg", "assets/img/props/20/p2.jpg", "assets/img/props/20/p3.jpg", "assets/img/props/20/p4.jpg", "assets/img/props/20/p5.jpg"]
  },
  {
    id: 15,
    title: {"en": "Energy-Efficient Family Home", "de": "Energieeffizientes Familienhaus"},
    status: "sale",
    type: "detached",
    price: 670000,
    location: {"en": "Waldstraßenviertel, Leipzig", "de": "Waldstraßenviertel, Leipzig"},
    beds: 5, baths: 4, sqm: 245,
    description: {"en": "A contemporary family home built to Kf70 standard: bright rooms, generous layout, air-to-air heat pump and a car port. Ideal for buyers moving in right away.", "de": "Ein modernes Familienhaus in Kf70-Bauweise: helle Räume, großzügiger Grundriss, Luft-Wasser-Wärmepumpe und Carport. Ideal für sofort Einziehende."},
    features: {"en": ["Car port", "Energy class A", "Architect design", "Fitted kitchen", "Garden & terrace"], "de": ["Carport", "Energieklasse A", "Architektenhaus", "Einbauküche", "Garten & Terrasse"]},
    image: "assets/img/props/29/p1.jpg",
    gallery: ["assets/img/props/29/p1.jpg", "assets/img/props/29/p2.jpg", "assets/img/props/29/p3.jpg", "assets/img/props/29/p4.jpg", "assets/img/props/29/p5.jpg"]
  },
  {
    id: 16,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 1412,
    priceNote: "per_month",
    location: {"en": "Friedenau, Berlin", "de": "Friedenau, Berlin"},
    beds: 3, baths: 2, sqm: 91,
    badge: {"en": "Garden", "de": "Garten"},
    description: {"en": "A lovingly modernized 4-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Friedenau.", "de": "Eine liebevoll modernisierte 4-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Friedenau."},
    features: {"en": ["Daylight bathroom", "Altbau charm", "Stucco ceilings", "Elevator", "Fitted kitchen"], "de": ["Tageslichtbad", "Altbau-Charme", "Stuckdecken", "Aufzug", "Einbauküche"]},
    image: "assets/img/props/58/p1.jpg",
    gallery: ["assets/img/props/58/p1.jpg", "assets/img/props/58/p2.jpg", "assets/img/props/58/p3.jpg", "assets/img/props/58/p4.jpg", "assets/img/props/58/p5.jpg"]
  },
  {
    id: 17,
    title: {"en": "Bright 4-Room Altbau Apartment", "de": "Helle 4-Zimmer-Altbauwohnung"},
    status: "rent",
    type: "apartment",
    price: 1228,
    priceNote: "per_month",
    location: {"en": "Oberkassel, Düsseldorf", "de": "Oberkassel, Düsseldorf"},
    beds: 3, baths: 2, sqm: 133,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "Classic Altbau with high stucco ceilings and wooden floors, freshly renovated in the heart of Oberkassel. U/S-Bahn, cafés and parks in walking distance.", "de": "Klassischer Altbau mit Stuckdecken und Holzböden, frisch renoviert im Herzen von Oberkassel. U/S-Bahn, Cafés und Parks in Gehweite."},
    features: {"en": ["Altbau charm", "Fitted kitchen", "Cellar space", "Elevator", "Daylight bathroom", "Wooden floors"], "de": ["Altbau-Charme", "Einbauküche", "Kellerabteil", "Aufzug", "Tageslichtbad", "Holzböden"]},
    image: "assets/img/props/48/p1.jpg",
    gallery: ["assets/img/props/48/p1.jpg", "assets/img/props/48/p2.jpg", "assets/img/props/48/p3.jpg", "assets/img/props/48/p4.jpg", "assets/img/props/48/p5.jpg"]
  },
  {
    id: 18,
    title: {"en": "Maisonette Apartment with Roof Terrace", "de": "Maisonette-Wohnung mit Dachterrasse"},
    status: "sale",
    type: "duplex",
    price: 920000,
    location: {"en": "West, Stuttgart", "de": "West, Stuttgart"},
    beds: 4, baths: 3, sqm: 139,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "A maisonette over two levels with a private roof terrace, open kitchen-living area and views across West.", "de": "Eine Maisonette über zwei Ebenen mit privater Dachterrasse, offener Küchen-Wohnfläche und Blick über West, Stuttgart."},
    features: {"en": ["Two levels", "Open kitchen-living", "Two balconies", "Elevator", "Underfloor heating"], "de": ["Zwei Ebenen", "Offene Küchen-Wohnfläche", "Zwei Balkone", "Aufzug", "Fußbodenheizung"]},
    image: "assets/img/props/45/p1.jpg",
    gallery: ["assets/img/props/45/p1.jpg", "assets/img/props/45/p2.jpg", "assets/img/props/45/p3.jpg", "assets/img/props/45/p4.jpg", "assets/img/props/45/p5.jpg"]
  },
  {
    id: 19,
    title: {"en": "Modern Villa with Garden in Zehlendorf", "de": "Moderne Villa mit Garten in Zehlendorf, Berlin"},
    status: "sale",
    type: "detached",
    price: 1930000,
    location: {"en": "Zehlendorf, Berlin", "de": "Zehlendorf, Berlin"},
    beds: 5, baths: 4, sqm: 407,
    description: {"en": "An architect-designed villa in one of Zehlendorf's most sought-after streets. Floor-to-ceiling windows, open-plan living, high-spec kitchen and a southwest-facing garden.", "de": "Eine vom Architekten entworfene Villa in einer der begehrtesten Lagen von Zehlendorf, Berlin. Bodenhohe Fenster, offenes Wohnen, hochwertige Küche und Süd-West-Garten."},
    features: {"en": ["Underfloor heating", "Smart home", "Garden & terrace", "Fitted kitchen", "Car port", "Architect design"], "de": ["Fußbodenheizung", "Smart Home", "Garten & Terrasse", "Einbauküche", "Carport", "Architektenhaus"]},
    image: "assets/img/props/31/p1.jpg",
    gallery: ["assets/img/props/31/p1.jpg", "assets/img/props/31/p2.jpg", "assets/img/props/31/p3.jpg", "assets/img/props/31/p4.jpg", "assets/img/props/31/p5.jpg"]
  },
  {
    id: 20,
    title: {"en": "Energy-Efficient Family Home", "de": "Energieeffizientes Familienhaus"},
    status: "sale",
    type: "detached",
    price: 1120000,
    location: {"en": "Blasewitz, Dresden", "de": "Blasewitz, Dresden"},
    beds: 6, baths: 4, sqm: 377,
    featured: true,
    description: {"en": "A contemporary family home built to Kf70 standard: bright rooms, generous layout, air-to-air heat pump and a car port. Ideal for buyers moving in right away.", "de": "Ein modernes Familienhaus in Kf70-Bauweise: helle Räume, großzügiger Grundriss, Luft-Wasser-Wärmepumpe und Carport. Ideal für sofort Einziehende."},
    features: {"en": ["Energy class A", "Architect design", "Underfloor heating", "Garden & terrace", "Smart home"], "de": ["Energieklasse A", "Architektenhaus", "Fußbodenheizung", "Garten & Terrasse", "Smart Home"]},
    image: "assets/img/props/32/p1.jpg",
    gallery: ["assets/img/props/32/p1.jpg", "assets/img/props/32/p2.jpg", "assets/img/props/32/p3.jpg", "assets/img/props/32/p4.jpg", "assets/img/props/32/p5.jpg"]
  },
  {
    id: 21,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 760,
    priceNote: "per_month",
    location: {"en": "Oberkassel, Düsseldorf", "de": "Oberkassel, Düsseldorf"},
    beds: 2, baths: 2, sqm: 65,
    description: {"en": "A lovingly modernized 3-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Oberkassel.", "de": "Eine liebevoll modernisierte 3-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Oberkassel."},
    features: {"en": ["Fitted kitchen", "Wooden floors", "Elevator", "Daylight bathroom", "Cellar space", "Stucco ceilings"], "de": ["Einbauküche", "Holzböden", "Aufzug", "Tageslichtbad", "Kellerabteil", "Stuckdecken"]},
    image: "assets/img/props/52/p1.jpg",
    gallery: ["assets/img/props/52/p1.jpg", "assets/img/props/52/p2.jpg", "assets/img/props/52/p3.jpg", "assets/img/props/52/p4.jpg", "assets/img/props/52/p5.jpg"]
  },
  {
    id: 22,
    title: {"en": "Renovated Half-Timbered House in Wernigerode", "de": "Renoviertes Fachwerkhaus in Wernigerode"},
    status: "sale",
    type: "detached",
    price: 460000,
    location: {"en": "Wernigerode, Germany", "de": "Wernigerode"},
    beds: 4, baths: 2, sqm: 245,
    description: {"en": "A beautifully renovated half-timbered house in Wernigerode. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 245 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Wernigerode. Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 245 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Underfloor heating", "Timber facade restored", "Energy certificate class C", "Fitted kitchen", "Renovated 2021", "Courtyard garden", "Listed landmark charm"], "de": ["Fußbodenheizung", "Fassade restauriert", "Energieklasse C", "Einbauküche", "Saniert 2021", "Innenhofgarten", "Denkmal-Charme"]},
    image: "assets/img/props/6/p1.jpg",
    gallery: ["assets/img/props/6/p1.jpg", "assets/img/props/6/p2.jpg", "assets/img/props/6/p3.jpg", "assets/img/props/6/p4.jpg", "assets/img/props/6/p5.jpg"]
  },
  {
    id: 23,
    title: {"en": "Modern Villa with Garden in Derendorf", "de": "Moderne Villa mit Garten in Derendorf, Düsseldorf"},
    status: "sale",
    type: "detached",
    price: 1820000,
    location: {"en": "Derendorf, Düsseldorf", "de": "Derendorf, Düsseldorf"},
    beds: 4, baths: 3, sqm: 240,
    badge: {"en": "Luxury", "de": "Luxus"},
    description: {"en": "An architect-designed villa in one of Derendorf's most sought-after streets. Floor-to-ceiling windows, open-plan living, high-spec kitchen and a southwest-facing garden.", "de": "Eine vom Architekten entworfene Villa in einer der begehrtesten Lagen von Derendorf, Düsseldorf. Bodenhohe Fenster, offenes Wohnen, hochwertige Küche und Süd-West-Garten."},
    features: {"en": ["Energy class A", "Underfloor heating", "Car port", "Architect design", "Smart home", "Garden & terrace", "Fitted kitchen"], "de": ["Energieklasse A", "Fußbodenheizung", "Carport", "Architektenhaus", "Smart Home", "Garten & Terrasse", "Einbauküche"]},
    image: "assets/img/props/30/p1.jpg",
    gallery: ["assets/img/props/30/p1.jpg", "assets/img/props/30/p2.jpg", "assets/img/props/30/p3.jpg", "assets/img/props/30/p4.jpg", "assets/img/props/30/p5.jpg"]
  },
  {
    id: 24,
    title: {"en": "Historic Half-Timbered House, Modernized", "de": "Historisches Fachwerkhaus, modernisiert"},
    status: "sale",
    type: "detached",
    price: 470000,
    location: {"en": "Ulm, Germany", "de": "Ulm (Baden-Württemberg)"},
    beds: 3, baths: 2, sqm: 258,
    badge: {"en": "Top offer", "de": "Top-Angebot"},
    description: {"en": "Living behind a listed timber facade: this 258 m² house in Ulm combines 19th-century charm with a contemporary interior, underfloor heating and a renovated roof.", "de": "Wohnen hinter denkmalgeschützter Fachwerkfassade: dieses 258 m² Haus in Ulm (Baden-Württemberg) verbindet Charme des 19. Jahrhunderts mit modernem Interieur, Fußbodenheizung und saniertem Dach."},
    features: {"en": ["Listed landmark charm", "Courtyard garden", "Renovated 2021", "Timber facade restored", "Fitted kitchen", "Underfloor heating"], "de": ["Denkmal-Charme", "Innenhofgarten", "Saniert 2021", "Fassade restauriert", "Einbauküche", "Fußbodenheizung"]},
    image: "assets/img/props/11/p1.jpg",
    gallery: ["assets/img/props/11/p1.jpg", "assets/img/props/11/p2.jpg", "assets/img/props/11/p3.jpg", "assets/img/props/11/p4.jpg", "assets/img/props/11/p5.jpg"]
  },
  {
    id: 25,
    title: {"en": "Apartment in Historic Half-Timbered House", "de": "Wohnung im historischen Fachwerkhaus"},
    status: "rent",
    type: "apartment",
    price: 977,
    priceNote: "per_month",
    location: {"en": "Tübingen, Germany", "de": "Tübingen"},
    beds: 3, baths: 2, sqm: 71,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "Bright 71 m² apartment on the upper floor of a landmark half-timbered house in the old town of Tübingen. High ceilings, wooden floors and a view over the rooftops.", "de": "Helle 71 m² Wohnung im Obergeschoss eines denkmalgeschützten Fachwerkhauses in der Altstadt von Tübingen. Hohe Decken, Holzböden und Blick über die Dächer."},
    features: {"en": ["Old-town location", "Cellar space", "High ceilings", "Fitted kitchen", "Rooftop view"], "de": ["Altstadtlage", "Kellerabteil", "Hohe Decken", "Einbauküche", "Blick über Dächer"]},
    image: "assets/img/props/19/p1.jpg",
    gallery: ["assets/img/props/19/p1.jpg", "assets/img/props/19/p2.jpg", "assets/img/props/19/p3.jpg", "assets/img/props/19/p4.jpg", "assets/img/props/19/p5.jpg"]
  },
  {
    id: 26,
    title: {"en": "Modern Villa with Garden in Vaihingen", "de": "Moderne Villa mit Garten in Vaihingen, Stuttgart"},
    status: "sale",
    type: "detached",
    price: 1090000,
    location: {"en": "Vaihingen, Stuttgart", "de": "Vaihingen, Stuttgart"},
    beds: 4, baths: 4, sqm: 273,
    featured: true,
    description: {"en": "An architect-designed villa in one of Vaihingen's most sought-after streets. Floor-to-ceiling windows, open-plan living, high-spec kitchen and a southwest-facing garden.", "de": "Eine vom Architekten entworfene Villa in einer der begehrtesten Lagen von Vaihingen, Stuttgart. Bodenhohe Fenster, offenes Wohnen, hochwertige Küche und Süd-West-Garten."},
    features: {"en": ["Energy class A", "Underfloor heating", "Smart home", "Car port", "Garden & terrace", "Fitted kitchen"], "de": ["Energieklasse A", "Fußbodenheizung", "Smart Home", "Carport", "Garten & Terrasse", "Einbauküche"]},
    image: "assets/img/props/33/p1.jpg",
    gallery: ["assets/img/props/33/p1.jpg", "assets/img/props/33/p2.jpg", "assets/img/props/33/p3.jpg", "assets/img/props/33/p4.jpg", "assets/img/props/33/p5.jpg"]
  },
  {
    id: 27,
    title: {"en": "Detached House with Mature Garden", "de": "Freistehendes Haus mit altem Garten"},
    status: "sale",
    type: "detached",
    price: 1150000,
    location: {"en": "Plagwitz, Leipzig", "de": "Plagwitz, Leipzig"},
    beds: 4, baths: 3, sqm: 279,
    description: {"en": "A well-kept detached home with 279 m² of living space, a mature garden and a quiet, established neighbourhood in Plagwitz.", "de": "Ein gepflegtes freistehendes Haus mit 279 m² Wohnfläche, altem Baumbestand und ruhiger, etablierter Nachbarschaft in Plagwitz, Leipzig."},
    features: {"en": ["Energy class A", "Architect design", "Fitted kitchen", "Car port", "Smart home"], "de": ["Energieklasse A", "Architektenhaus", "Einbauküche", "Carport", "Smart Home"]},
    image: "assets/img/props/28/p1.jpg",
    gallery: ["assets/img/props/28/p1.jpg", "assets/img/props/28/p2.jpg", "assets/img/props/28/p3.jpg", "assets/img/props/28/p4.jpg", "assets/img/props/28/p5.jpg"]
  },
  {
    id: 28,
    title: {"en": "Detached House with Mature Garden", "de": "Freistehendes Haus mit altem Garten"},
    status: "sale",
    type: "detached",
    price: 750000,
    location: {"en": "Plagwitz, Leipzig", "de": "Plagwitz, Leipzig"},
    beds: 5, baths: 4, sqm: 197,
    description: {"en": "A well-kept detached home with 197 m² of living space, a mature garden and a quiet, established neighbourhood in Plagwitz.", "de": "Ein gepflegtes freistehendes Haus mit 197 m² Wohnfläche, altem Baumbestand und ruhiger, etablierter Nachbarschaft in Plagwitz, Leipzig."},
    features: {"en": ["Energy class A", "Garden & terrace", "Fitted kitchen", "Smart home", "Architect design", "Underfloor heating", "Car port"], "de": ["Energieklasse A", "Garten & Terrasse", "Einbauküche", "Smart Home", "Architektenhaus", "Fußbodenheizung", "Carport"]},
    image: "assets/img/props/26/p1.jpg",
    gallery: ["assets/img/props/26/p1.jpg", "assets/img/props/26/p2.jpg", "assets/img/props/26/p3.jpg", "assets/img/props/26/p4.jpg", "assets/img/props/26/p5.jpg"]
  },
  {
    id: 29,
    title: {"en": "Detached House with Mature Garden", "de": "Freistehendes Haus mit altem Garten"},
    status: "sale",
    type: "detached",
    price: 1880000,
    location: {"en": "Westend, Frankfurt", "de": "Westend, Frankfurt am Main"},
    beds: 6, baths: 3, sqm: 315,
    description: {"en": "A well-kept detached home with 315 m² of living space, a mature garden and a quiet, established neighbourhood in Westend.", "de": "Ein gepflegtes freistehendes Haus mit 315 m² Wohnfläche, altem Baumbestand und ruhiger, etablierter Nachbarschaft in Westend, Frankfurt am Main."},
    features: {"en": ["Smart home", "Energy class A", "Garden & terrace", "Car port", "Architect design", "Underfloor heating"], "de": ["Smart Home", "Energieklasse A", "Garten & Terrasse", "Carport", "Architektenhaus", "Fußbodenheizung"]},
    image: "assets/img/props/34/p1.jpg",
    gallery: ["assets/img/props/34/p1.jpg", "assets/img/props/34/p2.jpg", "assets/img/props/34/p3.jpg", "assets/img/props/34/p4.jpg", "assets/img/props/34/p5.jpg"]
  },
  {
    id: 30,
    title: {"en": "Maisonette Apartment with Roof Terrace", "de": "Maisonette-Wohnung mit Dachterrasse"},
    status: "sale",
    type: "duplex",
    price: 680000,
    location: {"en": "Oberkassel, Düsseldorf", "de": "Oberkassel, Düsseldorf"},
    beds: 3, baths: 2, sqm: 124,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "A maisonette over two levels with a private roof terrace, open kitchen-living area and views across Oberkassel.", "de": "Eine Maisonette über zwei Ebenen mit privater Dachterrasse, offener Küchen-Wohnfläche und Blick über Oberkassel, Düsseldorf."},
    features: {"en": ["Two balconies", "Underfloor heating", "Elevator", "Two levels", "Roof terrace", "Open kitchen-living"], "de": ["Zwei Balkone", "Fußbodenheizung", "Aufzug", "Zwei Ebenen", "Dachterrasse", "Offene Küchen-Wohnfläche"]},
    image: "assets/img/props/40/p1.jpg",
    gallery: ["assets/img/props/40/p1.jpg", "assets/img/props/40/p2.jpg", "assets/img/props/40/p3.jpg", "assets/img/props/40/p4.jpg", "assets/img/props/40/p5.jpg"]
  },
  {
    id: 31,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 1258,
    priceNote: "per_month",
    location: {"en": "Lindenthal, Cologne", "de": "Lindenthal, Köln"},
    beds: 1, baths: 1, sqm: 116,
    featured: true,
    description: {"en": "A lovingly modernized 2-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Lindenthal.", "de": "Eine liebevoll modernisierte 2-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Lindenthal."},
    features: {"en": ["Fitted kitchen", "Stucco ceilings", "Daylight bathroom", "Altbau charm", "Elevator", "Balcony", "Wooden floors"], "de": ["Einbauküche", "Stuckdecken", "Tageslichtbad", "Altbau-Charme", "Aufzug", "Balkon", "Holzböden"]},
    image: "assets/img/props/50/p1.jpg",
    gallery: ["assets/img/props/50/p1.jpg", "assets/img/props/50/p2.jpg", "assets/img/props/50/p3.jpg", "assets/img/props/50/p4.jpg", "assets/img/props/50/p5.jpg"]
  },
  {
    id: 32,
    title: {"en": "Penthouse with Roof Terrace", "de": "Penthouse mit Dachterrasse"},
    status: "sale",
    type: "penthouse",
    price: 2900000,
    location: {"en": "Neuhausen, Munich", "de": "Neuhausen, München"},
    beds: 3, baths: 2, sqm: 203,
    description: {"en": "A top-floor penthouse with wrap-around roof terrace and open skyline views over Neuhausen. Elevator access, underfloor heating and two parking bays in the building's garage.", "de": "Ein Penthouse im Obergeschoss mit umlaufender Dachterrasse und freiem Blick über Neuhausen. Aufzug, Fußbodenheizung und zwei Stellplätze im Haus."},
    features: {"en": ["Roof terrace", "Elevator", "Underfloor heating", "Concierge", "Two parking bays"], "de": ["Dachterrasse", "Aufzug", "Fußbodenheizung", "Concierge", "Zwei Stellplätze"]},
    image: "assets/img/props/59/p1.jpg",
    gallery: ["assets/img/props/59/p1.jpg", "assets/img/props/59/p2.jpg", "assets/img/props/59/p3.jpg", "assets/img/props/59/p4.jpg", "assets/img/props/59/p5.jpg"]
  },
  {
    id: 33,
    title: {"en": "Charming Fachwerk House with Garden", "de": "Charmantes Fachwerkhaus mit Garten"},
    status: "sale",
    type: "detached",
    price: 450000,
    location: {"en": "Tübingen, Germany", "de": "Tübingen"},
    beds: 5, baths: 3, sqm: 166,
    description: {"en": "Typical German half-timbered house from the historic centre of Tübingen, fully modernized in recent years. Wooden beams, high ceilings and a quiet courtyard garden create a unique home.", "de": "Typisches deutsches Fachwerkhaus aus dem historischen Altstadtkern von Tübingen, in den letzten Jahren vollmodernisiert. Deckenbalken, hohe Räume und ein ruhiger Innenhofgarten machen das Objekt besonders."},
    features: {"en": ["Listed landmark charm", "Renovated 2021", "Energy certificate class C", "Underfloor heating", "Courtyard garden", "Timber facade restored"], "de": ["Denkmal-Charme", "Saniert 2021", "Energieklasse C", "Fußbodenheizung", "Innenhofgarten", "Fassade restauriert"]},
    image: "assets/img/props/8/p1.jpg",
    gallery: ["assets/img/props/8/p1.jpg", "assets/img/props/8/p2.jpg", "assets/img/props/8/p3.jpg", "assets/img/props/8/p4.jpg", "assets/img/props/8/p5.jpg"]
  },
  {
    id: 34,
    title: {"en": "Renovated Half-Timbered House in Celle", "de": "Renoviertes Fachwerkhaus in Celle"},
    status: "sale",
    type: "detached",
    price: 650000,
    location: {"en": "Celle, Germany", "de": "Celle"},
    beds: 4, baths: 2, sqm: 240,
    badge: {"en": "Garden", "de": "Garten"},
    description: {"en": "A beautifully renovated half-timbered house in Celle. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 240 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Celle. Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 240 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Energy certificate class C", "Fitted kitchen", "Timber facade restored", "Renovated 2021", "Listed landmark charm"], "de": ["Energieklasse C", "Einbauküche", "Fassade restauriert", "Saniert 2021", "Denkmal-Charme"]},
    image: "assets/img/props/12/p1.jpg",
    gallery: ["assets/img/props/12/p1.jpg", "assets/img/props/12/p2.jpg", "assets/img/props/12/p3.jpg", "assets/img/props/12/p4.jpg", "assets/img/props/12/p5.jpg"]
  },
  {
    id: 35,
    title: {"en": "Apartment in Historic Half-Timbered House", "de": "Wohnung im historischen Fachwerkhaus"},
    status: "rent",
    type: "apartment",
    price: 659,
    priceNote: "per_month",
    location: {"en": "Marburg, Germany", "de": "Marburg"},
    beds: 1, baths: 2, sqm: 92,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "Bright 92 m² apartment on the upper floor of a landmark half-timbered house in the old town of Marburg. High ceilings, wooden floors and a view over the rooftops.", "de": "Helle 92 m² Wohnung im Obergeschoss eines denkmalgeschützten Fachwerkhauses in der Altstadt von Marburg. Hohe Decken, Holzböden und Blick über die Dächer."},
    features: {"en": ["Wooden floors", "Fitted kitchen", "Cellar space", "Old-town location", "Rooftop view", "High ceilings"], "de": ["Holzböden", "Einbauküche", "Kellerabteil", "Altstadtlage", "Blick über Dächer", "Hohe Decken"]},
    image: "assets/img/props/17/p1.jpg",
    gallery: ["assets/img/props/17/p1.jpg", "assets/img/props/17/p2.jpg", "assets/img/props/17/p3.jpg", "assets/img/props/17/p4.jpg", "assets/img/props/17/p5.jpg"]
  },
  {
    id: 36,
    title: {"en": "Single-Level Bungalow by the Outskirts", "de": "Ebenengeschossener Bungalow am Stadtrand"},
    status: "sale",
    type: "bungalow",
    price: 980000,
    location: {"en": "Sachsenhausen, Frankfurt", "de": "Sachsenhausen, Frankfurt am Main"},
    beds: 3, baths: 2, sqm: 145,
    featured: true,
    description: {"en": "Single-level living at its best: this bungalow offers 145 m² on one floor, a wrap-around terrace and step-free access throughout.", "de": "Wohnen auf einer Ebene: dieser Bungalow bietet 145 m² auf einem Geschoss, umlaufende Terrasse und barrierefreien Zugang."},
    features: {"en": ["Garage", "Garden", "Step-free access", "Wrap-around terrace", "Heat pump", "Single-level layout"], "de": ["Garage", "Garten", "Barrierefrei", "Umlaufende Terrasse", "Wärmepumpe", "Ebenerdig"]},
    image: "assets/img/props/35/p1.jpg",
    gallery: ["assets/img/props/35/p1.jpg", "assets/img/props/35/p2.jpg", "assets/img/props/35/p3.jpg", "assets/img/props/35/p4.jpg", "assets/img/props/35/p5.jpg"]
  },
  {
    id: 37,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 1085,
    priceNote: "per_month",
    location: {"en": "Connewitz, Leipzig", "de": "Connewitz, Leipzig"},
    beds: 3, baths: 2, sqm: 112,
    badge: {"en": "Garden", "de": "Garten"},
    description: {"en": "A lovingly modernized 4-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Connewitz.", "de": "Eine liebevoll modernisierte 4-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Connewitz."},
    features: {"en": ["Daylight bathroom", "Altbau charm", "Cellar space", "Stucco ceilings", "Wooden floors", "Balcony"], "de": ["Tageslichtbad", "Altbau-Charme", "Kellerabteil", "Stuckdecken", "Holzböden", "Balkon"]},
    image: "assets/img/props/54/p1.jpg",
    gallery: ["assets/img/props/54/p1.jpg", "assets/img/props/54/p2.jpg", "assets/img/props/54/p3.jpg", "assets/img/props/54/p4.jpg", "assets/img/props/54/p5.jpg"]
  },
  {
    id: 38,
    title: {"en": "Maisonette Apartment with Roof Terrace", "de": "Maisonette-Wohnung mit Dachterrasse"},
    status: "sale",
    type: "duplex",
    price: 740000,
    location: {"en": "Johannis, Nuremberg", "de": "Johannis, Nürnberg"},
    beds: 4, baths: 3, sqm: 153,
    description: {"en": "A maisonette over two levels with a private roof terrace, open kitchen-living area and views across Johannis.", "de": "Eine Maisonette über zwei Ebenen mit privater Dachterrasse, offener Küchen-Wohnfläche und Blick über Johannis, Nürnberg."},
    features: {"en": ["Roof terrace", "Underfloor heating", "Two balconies", "Two levels", "Open kitchen-living", "Elevator"], "de": ["Dachterrasse", "Fußbodenheizung", "Zwei Balkone", "Zwei Ebenen", "Offene Küchen-Wohnfläche", "Aufzug"]},
    image: "assets/img/props/42/p1.jpg",
    gallery: ["assets/img/props/42/p1.jpg", "assets/img/props/42/p2.jpg", "assets/img/props/42/p3.jpg", "assets/img/props/42/p4.jpg", "assets/img/props/42/p5.jpg"]
  },
  {
    id: 39,
    title: {"en": "Apartment in Historic Half-Timbered House", "de": "Wohnung im historischen Fachwerkhaus"},
    status: "rent",
    type: "apartment",
    price: 728,
    priceNote: "per_month",
    location: {"en": "Dinkelsbühl, Germany", "de": "Dinkelsbühl"},
    beds: 1, baths: 2, sqm: 102,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "Bright 102 m² apartment on the upper floor of a landmark half-timbered house in the old town of Dinkelsbühl. High ceilings, wooden floors and a view over the rooftops.", "de": "Helle 102 m² Wohnung im Obergeschoss eines denkmalgeschützten Fachwerkhauses in der Altstadt von Dinkelsbühl. Hohe Decken, Holzböden und Blick über die Dächer."},
    features: {"en": ["Old-town location", "Fitted kitchen", "Cellar space", "Rooftop view", "Wooden floors", "High ceilings"], "de": ["Altstadtlage", "Einbauküche", "Kellerabteil", "Blick über Dächer", "Holzböden", "Hohe Decken"]},
    image: "assets/img/props/18/p1.jpg",
    gallery: ["assets/img/props/18/p1.jpg", "assets/img/props/18/p2.jpg", "assets/img/props/18/p3.jpg", "assets/img/props/18/p4.jpg", "assets/img/props/18/p5.jpg"]
  },
  {
    id: 40,
    title: {"en": "Historic Half-Timbered House, Modernized", "de": "Historisches Fachwerkhaus, modernisiert"},
    status: "sale",
    type: "detached",
    price: 310000,
    location: {"en": "Fritzlar, Germany", "de": "Fritzlar (Hessen)"},
    beds: 4, baths: 2, sqm: 260,
    description: {"en": "Living behind a listed timber facade: this 260 m² house in Fritzlar combines 19th-century charm with a contemporary interior, underfloor heating and a renovated roof.", "de": "Wohnen hinter denkmalgeschützter Fachwerkfassade: dieses 260 m² Haus in Fritzlar (Hessen) verbindet Charme des 19. Jahrhunderts mit modernem Interieur, Fußbodenheizung und saniertem Dach."},
    features: {"en": ["Courtyard garden", "Energy certificate class C", "Underfloor heating", "Fitted kitchen", "Listed landmark charm"], "de": ["Innenhofgarten", "Energieklasse C", "Fußbodenheizung", "Einbauküche", "Denkmal-Charme"]},
    image: "assets/img/props/1/p1.jpg",
    gallery: ["assets/img/props/1/p1.jpg", "assets/img/props/1/p2.jpg", "assets/img/props/1/p3.jpg", "assets/img/props/1/p4.jpg", "assets/img/props/1/p5.jpg"]
  },
  {
    id: 41,
    title: {"en": "Penthouse with Roof Terrace", "de": "Penthouse mit Dachterrasse"},
    status: "rent",
    type: "penthouse",
    price: 5954,
    priceNote: "per_month",
    location: {"en": "Sachsenhausen, Frankfurt", "de": "Sachsenhausen, Frankfurt am Main"},
    beds: 4, baths: 3, sqm: 209,
    description: {"en": "A top-floor penthouse with wrap-around roof terrace and open skyline views over Sachsenhausen. Elevator access, underfloor heating and two parking bays in the building's garage.", "de": "Ein Penthouse im Obergeschoss mit umlaufender Dachterrasse und freiem Blick über Sachsenhausen. Aufzug, Fußbodenheizung und zwei Stellplätze im Haus."},
    features: {"en": ["Concierge", "Roof terrace", "Underfloor heating", "Elevator", "Skyline view", "Two parking bays"], "de": ["Concierge", "Dachterrasse", "Fußbodenheizung", "Aufzug", "Ausblick", "Zwei Stellplätze"]},
    image: "assets/img/props/60/p1.jpg",
    gallery: ["assets/img/props/60/p1.jpg", "assets/img/props/60/p2.jpg", "assets/img/props/60/p3.jpg", "assets/img/props/60/p4.jpg", "assets/img/props/60/p5.jpg"]
  },
  {
    id: 42,
    title: {"en": "Historic Half-Timbered House, Modernized", "de": "Historisches Fachwerkhaus, modernisiert"},
    status: "sale",
    type: "detached",
    price: 540000,
    location: {"en": "Görlitz, Germany", "de": "Görlitz"},
    beds: 3, baths: 2, sqm: 183,
    badge: {"en": "Top offer", "de": "Top-Angebot"},
    featured: true,
    description: {"en": "Living behind a listed timber facade: this 183 m² house in Görlitz combines 19th-century charm with a contemporary interior, underfloor heating and a renovated roof.", "de": "Wohnen hinter denkmalgeschützter Fachwerkfassade: dieses 183 m² Haus in Görlitz verbindet Charme des 19. Jahrhunderts mit modernem Interieur, Fußbodenheizung und saniertem Dach."},
    features: {"en": ["Fitted kitchen", "Courtyard garden", "Energy certificate class C", "Listed landmark charm", "Timber facade restored", "Underfloor heating", "Renovated 2021"], "de": ["Einbauküche", "Innenhofgarten", "Energieklasse C", "Denkmal-Charme", "Fassade restauriert", "Fußbodenheizung", "Saniert 2021"]},
    image: "assets/img/props/10/p1.jpg",
    gallery: ["assets/img/props/10/p1.jpg", "assets/img/props/10/p2.jpg", "assets/img/props/10/p3.jpg", "assets/img/props/10/p4.jpg", "assets/img/props/10/p5.jpg"]
  },
  {
    id: 43,
    title: {"en": "Bright 2-Room Altbau Apartment", "de": "Helle 2-Zimmer-Altbauwohnung"},
    status: "rent",
    type: "apartment",
    price: 818,
    priceNote: "per_month",
    location: {"en": "Blankenese, Hamburg", "de": "Blankenese, Hamburg"},
    beds: 1, baths: 2, sqm: 114,
    description: {"en": "Classic Altbau with high stucco ceilings and wooden floors, freshly renovated in the heart of Blankenese. U/S-Bahn, cafés and parks in walking distance.", "de": "Klassischer Altbau mit Stuckdecken und Holzböden, frisch renoviert im Herzen von Blankenese. U/S-Bahn, Cafés und Parks in Gehweite."},
    features: {"en": ["Elevator", "Fitted kitchen", "Balcony", "Daylight bathroom", "Wooden floors"], "de": ["Aufzug", "Einbauküche", "Balkon", "Tageslichtbad", "Holzböden"]},
    image: "assets/img/props/56/p1.jpg",
    gallery: ["assets/img/props/56/p1.jpg", "assets/img/props/56/p2.jpg", "assets/img/props/56/p3.jpg", "assets/img/props/56/p4.jpg", "assets/img/props/56/p5.jpg"]
  },
  {
    id: 44,
    title: {"en": "Renovated Half-Timbered House in Quedlinburg", "de": "Renoviertes Fachwerkhaus in Quedlinburg (Sachsen-Anhalt)"},
    status: "sale",
    type: "detached",
    price: 450000,
    location: {"en": "Quedlinburg, Germany", "de": "Quedlinburg (Sachsen-Anhalt)"},
    beds: 4, baths: 2, sqm: 194,
    description: {"en": "A beautifully renovated half-timbered house in Quedlinburg. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 194 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Quedlinburg (Sachsen-Anhalt). Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 194 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Energy certificate class C", "Fitted kitchen", "Underfloor heating", "Courtyard garden", "Listed landmark charm"], "de": ["Energieklasse C", "Einbauküche", "Fußbodenheizung", "Innenhofgarten", "Denkmal-Charme"]},
    image: "assets/img/props/15/p1.jpg",
    gallery: ["assets/img/props/15/p1.jpg", "assets/img/props/15/p2.jpg", "assets/img/props/15/p3.jpg", "assets/img/props/15/p4.jpg", "assets/img/props/15/p5.jpg"]
  },
  {
    id: 45,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 1630,
    priceNote: "per_month",
    location: {"en": "Derendorf, Düsseldorf", "de": "Derendorf, Düsseldorf"},
    beds: 2, baths: 1, sqm: 89,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "A lovingly modernized 3-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Derendorf.", "de": "Eine liebevoll modernisierte 3-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Derendorf."},
    features: {"en": ["Fitted kitchen", "Cellar space", "Stucco ceilings", "Altbau charm", "Daylight bathroom"], "de": ["Einbauküche", "Kellerabteil", "Stuckdecken", "Altbau-Charme", "Tageslichtbad"]},
    image: "assets/img/props/47/p1.jpg",
    gallery: ["assets/img/props/47/p1.jpg", "assets/img/props/47/p2.jpg", "assets/img/props/47/p3.jpg", "assets/img/props/47/p4.jpg", "assets/img/props/47/p5.jpg"]
  },
  {
    id: 46,
    title: {"en": "Single-Level Bungalow by the Outskirts", "de": "Ebenengeschossener Bungalow am Stadtrand"},
    status: "sale",
    type: "bungalow",
    price: 490000,
    location: {"en": "Ehrenfeld, Cologne", "de": "Ehrenfeld, Köln"},
    beds: 3, baths: 1, sqm: 170,
    description: {"en": "Single-level living at its best: this bungalow offers 170 m² on one floor, a wrap-around terrace and step-free access throughout.", "de": "Wohnen auf einer Ebene: dieser Bungalow bietet 170 m² auf einem Geschoss, umlaufende Terrasse und barrierefreien Zugang."},
    features: {"en": ["Garden", "Single-level layout", "Heat pump", "Garage", "Step-free access", "Wrap-around terrace"], "de": ["Garten", "Ebenerdig", "Wärmepumpe", "Garage", "Barrierefrei", "Umlaufende Terrasse"]},
    image: "assets/img/props/38/p1.jpg",
    gallery: ["assets/img/props/38/p1.jpg", "assets/img/props/38/p2.jpg", "assets/img/props/38/p3.jpg", "assets/img/props/38/p4.jpg", "assets/img/props/38/p5.jpg"]
  },
  {
    id: 47,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 1637,
    priceNote: "per_month",
    location: {"en": "Bad Cannstatt, Stuttgart", "de": "Bad Cannstatt, Stuttgart"},
    beds: 1, baths: 2, sqm: 76,
    badge: {"en": "Garden", "de": "Garten"},
    featured: true,
    description: {"en": "A lovingly modernized 2-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Bad Cannstatt.", "de": "Eine liebevoll modernisierte 2-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Bad Cannstatt."},
    features: {"en": ["Elevator", "Balcony", "Stucco ceilings", "Daylight bathroom", "Fitted kitchen", "Altbau charm"], "de": ["Aufzug", "Balkon", "Stuckdecken", "Tageslichtbad", "Einbauküche", "Altbau-Charme"]},
    image: "assets/img/props/53/p1.jpg",
    gallery: ["assets/img/props/53/p1.jpg", "assets/img/props/53/p2.jpg", "assets/img/props/53/p3.jpg", "assets/img/props/53/p4.jpg", "assets/img/props/53/p5.jpg"]
  },
  {
    id: 48,
    title: {"en": "Single-Level Bungalow by the Outskirts", "de": "Ebenengeschossener Bungalow am Stadtrand"},
    status: "sale",
    type: "bungalow",
    price: 720000,
    location: {"en": "Lindenthal, Cologne", "de": "Lindenthal, Köln"},
    beds: 2, baths: 1, sqm: 163,
    description: {"en": "Single-level living at its best: this bungalow offers 163 m² on one floor, a wrap-around terrace and step-free access throughout.", "de": "Wohnen auf einer Ebene: dieser Bungalow bietet 163 m² auf einem Geschoss, umlaufende Terrasse und barrierefreien Zugang."},
    features: {"en": ["Step-free access", "Heat pump", "Garage", "Single-level layout", "Garden", "Wrap-around terrace"], "de": ["Barrierefrei", "Wärmepumpe", "Garage", "Ebenerdig", "Garten", "Umlaufende Terrasse"]},
    image: "assets/img/props/36/p1.jpg",
    gallery: ["assets/img/props/36/p1.jpg", "assets/img/props/36/p2.jpg", "assets/img/props/36/p3.jpg", "assets/img/props/36/p4.jpg", "assets/img/props/36/p5.jpg"]
  },
  {
    id: 49,
    title: {"en": "Renovated Altbau Apartment with Balcony", "de": "Renovierte Altbauwohnung mit Balkon"},
    status: "rent",
    type: "apartment",
    price: 1305,
    priceNote: "per_month",
    location: {"en": "Bornheim, Frankfurt", "de": "Bornheim, Frankfurt am Main"},
    beds: 1, baths: 2, sqm: 110,
    badge: {"en": "Garden", "de": "Garten"},
    description: {"en": "A lovingly modernized 2-room flat with balcony in a classic period building. Fitted kitchen, daylight bathroom and quiet courtyard side in Bornheim.", "de": "Eine liebevoll modernisierte 2-Zimmer-Wohnung mit Balkon im klassischen Gründerzeithaus. Einbauküche, Tageslichtbad und ruhige Hoflage in Bornheim."},
    features: {"en": ["Cellar space", "Daylight bathroom", "Balcony", "Wooden floors", "Altbau charm", "Stucco ceilings", "Fitted kitchen"], "de": ["Kellerabteil", "Tageslichtbad", "Balkon", "Holzböden", "Altbau-Charme", "Stuckdecken", "Einbauküche"]},
    image: "assets/img/props/49/p1.jpg",
    gallery: ["assets/img/props/49/p1.jpg", "assets/img/props/49/p2.jpg", "assets/img/props/49/p3.jpg", "assets/img/props/49/p4.jpg", "assets/img/props/49/p5.jpg"]
  },
  {
    id: 50,
    title: {"en": "Charming Fachwerk House with Garden", "de": "Charmantes Fachwerkhaus mit Garten"},
    status: "sale",
    type: "detached",
    price: 540000,
    location: {"en": "Rüdesheim, Germany", "de": "Rüdesheim"},
    beds: 3, baths: 3, sqm: 198,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "Typical German half-timbered house from the historic centre of Rüdesheim, fully modernized in recent years. Wooden beams, high ceilings and a quiet courtyard garden create a unique home.", "de": "Typisches deutsches Fachwerkhaus aus dem historischen Altstadtkern von Rüdesheim, in den letzten Jahren vollmodernisiert. Deckenbalken, hohe Räume und ein ruhiger Innenhofgarten machen das Objekt besonders."},
    features: {"en": ["Courtyard garden", "Underfloor heating", "Timber facade restored", "Energy certificate class C", "Renovated 2021", "Listed landmark charm"], "de": ["Innenhofgarten", "Fußbodenheizung", "Fassade restauriert", "Energieklasse C", "Saniert 2021", "Denkmal-Charme"]},
    image: "assets/img/props/5/p1.jpg",
    gallery: ["assets/img/props/5/p1.jpg", "assets/img/props/5/p2.jpg", "assets/img/props/5/p3.jpg", "assets/img/props/5/p4.jpg", "assets/img/props/5/p5.jpg"]
  },
  {
    id: 51,
    title: {"en": "Charming Fachwerk House with Garden", "de": "Charmantes Fachwerkhaus mit Garten"},
    status: "sale",
    type: "detached",
    price: 480000,
    location: {"en": "Monschau, Germany", "de": "Monschau"},
    beds: 5, baths: 3, sqm: 172,
    description: {"en": "Typical German half-timbered house from the historic centre of Monschau, fully modernized in recent years. Wooden beams, high ceilings and a quiet courtyard garden create a unique home.", "de": "Typisches deutsches Fachwerkhaus aus dem historischen Altstadtkern von Monschau, in den letzten Jahren vollmodernisiert. Deckenbalken, hohe Räume und ein ruhiger Innenhofgarten machen das Objekt besonders."},
    features: {"en": ["Listed landmark charm", "Energy certificate class C", "Fitted kitchen", "Courtyard garden", "Renovated 2021", "Underfloor heating", "Timber facade restored"], "de": ["Denkmal-Charme", "Energieklasse C", "Einbauküche", "Innenhofgarten", "Saniert 2021", "Fußbodenheizung", "Fassade restauriert"]},
    image: "assets/img/props/14/p1.jpg",
    gallery: ["assets/img/props/14/p1.jpg", "assets/img/props/14/p2.jpg", "assets/img/props/14/p3.jpg", "assets/img/props/14/p4.jpg", "assets/img/props/14/p5.jpg"]
  },
  {
    id: 52,
    title: {"en": "Single-Level Bungalow by the Outskirts", "de": "Ebenengeschossener Bungalow am Stadtrand"},
    status: "sale",
    type: "bungalow",
    price: 770000,
    location: {"en": "Oberkassel, Düsseldorf", "de": "Oberkassel, Düsseldorf"},
    beds: 2, baths: 1, sqm: 132,
    badge: {"en": "Popular", "de": "Gefragt"},
    featured: true,
    description: {"en": "Single-level living at its best: this bungalow offers 132 m² on one floor, a wrap-around terrace and step-free access throughout.", "de": "Wohnen auf einer Ebene: dieser Bungalow bietet 132 m² auf einem Geschoss, umlaufende Terrasse und barrierefreien Zugang."},
    features: {"en": ["Garage", "Garden", "Single-level layout", "Heat pump", "Wrap-around terrace"], "de": ["Garage", "Garten", "Ebenerdig", "Wärmepumpe", "Umlaufende Terrasse"]},
    image: "assets/img/props/37/p1.jpg",
    gallery: ["assets/img/props/37/p1.jpg", "assets/img/props/37/p2.jpg", "assets/img/props/37/p3.jpg", "assets/img/props/37/p4.jpg", "assets/img/props/37/p5.jpg"]
  },
  {
    id: 53,
    title: {"en": "Bright 3-Room Altbau Apartment", "de": "Helle 3-Zimmer-Altbauwohnung"},
    status: "rent",
    type: "apartment",
    price: 902,
    priceNote: "per_month",
    location: {"en": "Nippes, Cologne", "de": "Nippes, Köln"},
    beds: 2, baths: 2, sqm: 119,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "Classic Altbau with high stucco ceilings and wooden floors, freshly renovated in the heart of Nippes. U/S-Bahn, cafés and parks in walking distance.", "de": "Klassischer Altbau mit Stuckdecken und Holzböden, frisch renoviert im Herzen von Nippes. U/S-Bahn, Cafés und Parks in Gehweite."},
    features: {"en": ["Wooden floors", "Altbau charm", "Cellar space", "Daylight bathroom", "Fitted kitchen", "Stucco ceilings"], "de": ["Holzböden", "Altbau-Charme", "Kellerabteil", "Tageslichtbad", "Einbauküche", "Stuckdecken"]},
    image: "assets/img/props/57/p1.jpg",
    gallery: ["assets/img/props/57/p1.jpg", "assets/img/props/57/p2.jpg", "assets/img/props/57/p3.jpg", "assets/img/props/57/p4.jpg", "assets/img/props/57/p5.jpg"]
  },
  {
    id: 54,
    title: {"en": "Charming Fachwerk House with Garden", "de": "Charmantes Fachwerkhaus mit Garten"},
    status: "sale",
    type: "detached",
    price: 440000,
    location: {"en": "Fulda, Germany", "de": "Fulda (Hessen)"},
    beds: 3, baths: 3, sqm: 158,
    badge: {"en": "Garden", "de": "Garten"},
    description: {"en": "Typical German half-timbered house from the historic centre of Fulda, fully modernized in recent years. Wooden beams, high ceilings and a quiet courtyard garden create a unique home.", "de": "Typisches deutsches Fachwerkhaus aus dem historischen Altstadtkern von Fulda (Hessen), in den letzten Jahren vollmodernisiert. Deckenbalken, hohe Räume und ein ruhiger Innenhofgarten machen das Objekt besonders."},
    features: {"en": ["Underfloor heating", "Timber facade restored", "Courtyard garden", "Renovated 2021", "Energy certificate class C"], "de": ["Fußbodenheizung", "Fassade restauriert", "Innenhofgarten", "Saniert 2021", "Energieklasse C"]},
    image: "assets/img/props/9/p1.jpg",
    gallery: ["assets/img/props/9/p1.jpg", "assets/img/props/9/p2.jpg", "assets/img/props/9/p3.jpg", "assets/img/props/9/p4.jpg", "assets/img/props/9/p5.jpg"]
  },
  {
    id: 55,
    title: {"en": "Renovated Half-Timbered House in Heidelberg", "de": "Renoviertes Fachwerkhaus in Heidelberg"},
    status: "sale",
    type: "detached",
    price: 560000,
    location: {"en": "Heidelberg, Germany", "de": "Heidelberg"},
    beds: 5, baths: 3, sqm: 236,
    description: {"en": "A beautifully renovated half-timbered house in Heidelberg. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 236 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Heidelberg. Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 236 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Courtyard garden", "Fitted kitchen", "Timber facade restored", "Listed landmark charm", "Renovated 2021"], "de": ["Innenhofgarten", "Einbauküche", "Fassade restauriert", "Denkmal-Charme", "Saniert 2021"]},
    image: "assets/img/props/16/p1.jpg",
    gallery: ["assets/img/props/16/p1.jpg", "assets/img/props/16/p2.jpg", "assets/img/props/16/p3.jpg", "assets/img/props/16/p4.jpg", "assets/img/props/16/p5.jpg"]
  },
  {
    id: 56,
    title: {"en": "Apartment in Historic Half-Timbered House", "de": "Wohnung im historischen Fachwerkhaus"},
    status: "rent",
    type: "apartment",
    price: 891,
    priceNote: "per_month",
    location: {"en": "Alsfeld, Germany", "de": "Alsfeld"},
    beds: 3, baths: 1, sqm: 63,
    description: {"en": "Bright 63 m² apartment on the upper floor of a landmark half-timbered house in the old town of Alsfeld. High ceilings, wooden floors and a view over the rooftops.", "de": "Helle 63 m² Wohnung im Obergeschoss eines denkmalgeschützten Fachwerkhauses in der Altstadt von Alsfeld. Hohe Decken, Holzböden und Blick über die Dächer."},
    features: {"en": ["High ceilings", "Fitted kitchen", "Old-town location", "Cellar space", "Rooftop view", "Wooden floors"], "de": ["Hohe Decken", "Einbauküche", "Altstadtlage", "Kellerabteil", "Blick über Dächer", "Holzböden"]},
    image: "assets/img/props/22/p1.jpg",
    gallery: ["assets/img/props/22/p1.jpg", "assets/img/props/22/p2.jpg", "assets/img/props/22/p3.jpg", "assets/img/props/22/p4.jpg", "assets/img/props/22/p5.jpg"]
  },
  {
    id: 57,
    title: {"en": "Bright 4-Room Altbau Apartment", "de": "Helle 4-Zimmer-Altbauwohnung"},
    status: "rent",
    type: "apartment",
    price: 1612,
    priceNote: "per_month",
    location: {"en": "Vaihingen, Stuttgart", "de": "Vaihingen, Stuttgart"},
    beds: 3, baths: 1, sqm: 62,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "Classic Altbau with high stucco ceilings and wooden floors, freshly renovated in the heart of Vaihingen. U/S-Bahn, cafés and parks in walking distance.", "de": "Klassischer Altbau mit Stuckdecken und Holzböden, frisch renoviert im Herzen von Vaihingen. U/S-Bahn, Cafés und Parks in Gehweite."},
    features: {"en": ["Elevator", "Wooden floors", "Balcony", "Stucco ceilings", "Daylight bathroom", "Altbau charm", "Fitted kitchen"], "de": ["Aufzug", "Holzböden", "Balkon", "Stuckdecken", "Tageslichtbad", "Altbau-Charme", "Einbauküche"]},
    image: "assets/img/props/51/p1.jpg",
    gallery: ["assets/img/props/51/p1.jpg", "assets/img/props/51/p2.jpg", "assets/img/props/51/p3.jpg", "assets/img/props/51/p4.jpg", "assets/img/props/51/p5.jpg"]
  },
  {
    id: 58,
    title: {"en": "Renovated Half-Timbered House in Schieder-Schwalenberg", "de": "Renoviertes Fachwerkhaus in Schieder-Schwalenberg (Nordrhein-Westfalen)"},
    status: "sale",
    type: "detached",
    price: 410000,
    location: {"en": "Schieder-Schwalenberg, Germany", "de": "Schieder-Schwalenberg (Nordrhein-Westfalen)"},
    beds: 5, baths: 2, sqm: 206,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "A beautifully renovated half-timbered house in Schieder-Schwalenberg. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 206 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Schieder-Schwalenberg (Nordrhein-Westfalen). Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 206 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Timber facade restored", "Renovated 2021", "Energy certificate class C", "Fitted kitchen", "Listed landmark charm", "Underfloor heating", "Courtyard garden"], "de": ["Fassade restauriert", "Saniert 2021", "Energieklasse C", "Einbauküche", "Denkmal-Charme", "Fußbodenheizung", "Innenhofgarten"]},
    image: "assets/img/props/4/p1.jpg",
    gallery: ["assets/img/props/4/p1.jpg", "assets/img/props/4/p2.jpg", "assets/img/props/4/p3.jpg", "assets/img/props/4/p4.jpg", "assets/img/props/4/p5.jpg"]
  },
  {
    id: 59,
    title: {"en": "Renovated Half-Timbered House in Freiburg", "de": "Renoviertes Fachwerkhaus in Freiburg"},
    status: "sale",
    type: "detached",
    price: 490000,
    location: {"en": "Freiburg, Germany", "de": "Freiburg"},
    beds: 4, baths: 3, sqm: 250,
    badge: {"en": "Popular", "de": "Gefragt"},
    description: {"en": "A beautifully renovated half-timbered house in Freiburg. The historic facade hides a bright, modern interior: open living area, fitted kitchen, 250 m² of living space and a lovingly kept garden.", "de": "Ein wunderschön renoviertes Fachwerkhaus in Freiburg. Hinter der historischen Fassade verbirgt sich ein moderner, heller Innenraum: offener Wohnbereich, Einbauküche, 250 m² Wohnfläche und ein gepflegter Garten."},
    features: {"en": ["Renovated 2021", "Energy certificate class C", "Underfloor heating", "Courtyard garden", "Fitted kitchen"], "de": ["Saniert 2021", "Energieklasse C", "Fußbodenheizung", "Innenhofgarten", "Einbauküche"]},
    image: "assets/img/props/2/p1.jpg",
    gallery: ["assets/img/props/2/p1.jpg", "assets/img/props/2/p2.jpg", "assets/img/props/2/p3.jpg", "assets/img/props/2/p4.jpg", "assets/img/props/2/p5.jpg"]
  },
  {
    id: 60,
    title: {"en": "Single-Level Bungalow by the Outskirts", "de": "Ebenengeschossener Bungalow am Stadtrand"},
    status: "sale",
    type: "bungalow",
    price: 810000,
    location: {"en": "Zehlendorf, Berlin", "de": "Zehlendorf, Berlin"},
    beds: 2, baths: 2, sqm: 153,
    description: {"en": "Single-level living at its best: this bungalow offers 153 m² on one floor, a wrap-around terrace and step-free access throughout.", "de": "Wohnen auf einer Ebene: dieser Bungalow bietet 153 m² auf einem Geschoss, umlaufende Terrasse und barrierefreien Zugang."},
    features: {"en": ["Step-free access", "Heat pump", "Garden", "Wrap-around terrace", "Single-level layout", "Garage"], "de": ["Barrierefrei", "Wärmepumpe", "Garten", "Umlaufende Terrasse", "Ebenerdig", "Garage"]},
    image: "assets/img/props/39/p1.jpg",
    gallery: ["assets/img/props/39/p1.jpg", "assets/img/props/39/p2.jpg", "assets/img/props/39/p3.jpg", "assets/img/props/39/p4.jpg", "assets/img/props/39/p5.jpg"]
  },
  {
    id: 61,
    title: {"en": "Maisonette Apartment with Roof Terrace", "de": "Maisonette-Wohnung mit Dachterrasse"},
    status: "sale",
    type: "duplex",
    price: 450000,
    location: {"en": "Plagwitz, Leipzig", "de": "Plagwitz, Leipzig"},
    beds: 4, baths: 2, sqm: 140,
    badge: {"en": "New", "de": "Neu"},
    description: {"en": "A maisonette over two levels with a private roof terrace, open kitchen-living area and views across Plagwitz.", "de": "Eine Maisonette über zwei Ebenen mit privater Dachterrasse, offener Küchen-Wohnfläche und Blick über Plagwitz, Leipzig."},
    features: {"en": ["Open kitchen-living", "Two levels", "Roof terrace", "Elevator", "Two balconies"], "de": ["Offene Küchen-Wohnfläche", "Zwei Ebenen", "Dachterrasse", "Aufzug", "Zwei Balkone"]},
    image: "assets/img/props/41/p1.jpg",
    gallery: ["assets/img/props/41/p1.jpg", "assets/img/props/41/p2.jpg", "assets/img/props/41/p3.jpg", "assets/img/props/41/p4.jpg", "assets/img/props/41/p5.jpg"]
  },
];
